# Generated by Django 6.0.1 on 2026-03-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('face_distance', models.FloatField(default=0.0)),
                ('person_count', models.PositiveIntegerField(default=0)),
                ('suspicious_objects', models.JSONField(blank=True, default=list)),
                ('suspicion_delta', models.FloatField(default=0.0)),
                ('suspicion_total', models.FloatField(default=0.0)),
                ('face_suspicion', models.FloatField(default=0.0)),
                ('object_suspicion', models.FloatField(default=0.0)),
                ('person_suspicion', models.FloatField(default=0.0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.studentexamattempt')),
            ],
        ),
    ]
